schema_version: 1

context:
  version: "2.0.1"

package:
  name: openvkl
  version: ${{ version }}

source:
  url: https://github.com/RenderKit/openvkl/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0c7faa9582a93e93767afdb15a6c9c9ba154af7ee83a6b553705797be5f8af62

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ispc
    - ninja
  host:
    - embree
    - libboost-devel
    - openvdb
    - rkcommon ==1.14.0
    - tbb-devel
    - zlib
  run_exports:
    - ${{ pin_subpackage("openvkl", upper_bound="x") }}

tests:
  - package_contents:
      include:
        - openvkl/openvkl.h
      lib:
        - openvkl

about:
  homepage: https://www.openvkl.org
  repository: https://github.com/RenderKit/openvkl
  documentation: https://github.com/RenderKit/openvkl/blob/v${{ version }}/README.md
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Intel(R) Open Volume Kernel Library
  description: |
    Intel® Open Volume Kernel Library (Intel® Open VKL) is a collection of high performance volume computation kernels.

    With Open VKL, you can improve your volume rendering application using a wide variety of volumetric data structures, as well as performance-optimized traversal and sampling algorithms.

extra:
  recipe-maintainers:
    - eunos-1128
